#ifndef CONFIG_CA_CERT_H_
#define CONFIG_CA_CERT_H_
//content of ca.crt
const char ca_cert[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIBTTCB9QIUHxKNyOJESq1pw4VhiZxAIUx1CV0wCgYIKoZIzj0EAwIwKjETMBEG
A1UECgwKbXktY2EtbmFtZTETMBEGA1UEAwwKbXktY2EtbmFtZTAeFw0yMzA1MTMx
MjA3MTRaFw0yMzA2MTIxMjA3MTRaMCoxEzARBgNVBAoMCm15LWNhLW5hbWUxEzAR
BgNVBAMMCm15LWNhLW5hbWUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATWWdTX
ci5yqGMrOmiI3gI0aOhSthRa0BeVDEwuDwKDdkgnla0DcYP9HlDk+00mP+C/dasp
Z0Ad3Pm/z49QUp5OMAoGCCqGSM49BAMCA0cAMEQCICNJuM1B5TROi1M+ZUNd71cM
tku32rL529SnihpoMLaBAiA7E/RNvgFsAPjvzlQx5UiTMQuB+G2OoY/bQWrJJEdl
Kg==
-----END CERTIFICATE-----
)EOF";
#endif