#ifndef CONFIG_SERVER_KEY_H_
#define CONFIG_SERVER_KEY_H_
//content of server.key
const char server_private_key[] PROGMEM =R"EOF(
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIKEW/THApBwYWI9+m+rCIF99e7yQXxJoXIvt/PbTs2MLoAoGCCqGSM49
AwEHoUQDQgAEOL97upGaG1lA+D8UNYezbr48x98b9+tILVqoSL7WWsJNAzhbgCVV
VUmt0VtF6giHAFDMSjOkNMPZ0TgKaGXftQ==
-----END EC PRIVATE KEY-----
)EOF";
#endif