#ifndef CONFIG_SERVER_CERT_H_
#define CONFIG_SERVER_CERT_H_
//content of server.crt
const char server_cert[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIBVTCB/QIUImjbAVlar4YGqmffP7SfKDf7d4cwCgYIKoZIzj0EAwIwKjETMBEG
A1UECgwKbXktY2EtbmFtZTETMBEGA1UEAwwKbXktY2EtbmFtZTAeFw0yMzA1MTMx
MjA3MTRaFw0zNzAxMTkxMjA3MTRaMDIxFzAVBgNVBAoMDm15LXNlcnZlci1uYW1l
MRcwFQYDVQQDDA5teS1zZXJ2ZXItbmFtZTBZMBMGByqGSM49AgEGCCqGSM49AwEH
A0IABDi/e7qRmhtZQPg/FDWHs26+PMffG/frSC1aqEi+1lrCTQM4W4AlVVVJrdFb
ReoIhwBQzEozpDTD2dE4Cmhl37UwCgYIKoZIzj0EAwIDRwAwRAIgKZe4weXAQ2t6
iQkyEx8RM8FpkviQnRKDAz4V/vyWCagCIEM5i7mKI6xOcjk0aC8/Jm+vViqNSmc2
yWOY1LRkYgEh
-----END CERTIFICATE-----
)EOF";
#endif