#ifndef CONFIG_SERVER_KEY_H_
#define CONFIG_SERVER_KEY_H_
const char server_private_key[] PROGMEM =R"EOF(
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIFc/KRMD73CSJjWMwytDAbmX0mtTNhBxikkMVHY6uTmsoAoGCCqGSM49
AwEHoUQDQgAEFoDg6JZ29XeOcwiPqs6/NTKHxRkzD7gEsSm7b4i4aztZo6kXfkI0
kVq6iZnuG2Vv2m4G2NlbN85xXBhjOxJG3w==
-----END EC PRIVATE KEY-----
)EOF";
#endif